_wandb:
    value:
        cli_version: 0.26.1
        e:
            jebuy9tlxx1gasmlm5i3r831805hdtb4:
                codePath: src/main.py
                codePathLocal: main.py
                cpu_count: 9
                cpu_count_logical: 18
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "266206101504"
                        used: "178869960704"
                email: sergionik03@gmail.com
                executable: /home/ubuntu/analyse_review/.venv/bin/python3
                gpu: NVIDIA RTX A5000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-9099819e-5830-537d-0d17-0f677733e7c0
                host: vm5225
                memory:
                    total: "33641582592"
                os: Linux-5.15.0-176-generic-x86_64-with-glibc2.35
                program: /home/ubuntu/analyse_review/src/main.py
                python: CPython 3.12.13
                root: /home/ubuntu/analyse_review/src
                startedAt: "2026-04-28T10:46:39.656448Z"
                writerId: jebuy9tlxx1gasmlm5i3r831805hdtb4
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
            "3":
                - 16
            "4": 3.12.13
            "5": 0.26.1
            "6": 5.6.2
            "12": 0.26.1
            "13": linux-x86_64
batch_size:
    value: 32
dataset_path:
    value: data/imdb_dataset.csv
device:
    value: cuda
dropout:
    value: 0.3
embedding_dim:
    value: 300
hidden_dim:
    value: 128
learning_rate:
    value: "1e-3"
max_len:
    value: 512
num_classes:
    value: 2
num_epochs:
    value: 10
wandb_project:
    value: review_analysis
